import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./../components/providers/Providers";
import Navbar from "./../components/shared/Navbar";
import Footer from "./../components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BookWorm App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-370 mx-auto overflow-hidden flex flex-col items-center w-full">
          <Provider>
            <Navbar></Navbar>
            <div className="py-8"></div>
            {children}
            <Footer></Footer>
          </Provider>
        </div>
      </body>
    </html>
  );
}
