import LoginForm from "./LoginForm";

export const metadata = {
  title: "Login || BookWorm",
  description: "Generated by create next app",
};

const Login = () => {
  return <LoginForm></LoginForm>;
};

export default Login;
