import RegisterForm from "./RegisterForm";

export const metadata = {
  title: "Register || GameHub",
  description: "Generated by create next app",
};

export default function Page() {
  return <RegisterForm></RegisterForm>;
}
